version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Flask & Nginx 両方を 8080 でリスン
    volumes:
      - .:/app
    environment:
      FLASK_ENV: "production"
      FLASK_DEBUG: "False"
      SECRET_KEY: "mysecretkey"
    restart: unless-stopped
