version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: "development"    # 必要に応じて変更
      FLASK_DEBUG: "True"         # 必要に応じて変更
      SECRET_KEY: "mysecretkey"   # 必要に応じて変更
    restart: unless-stopped
