services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "5000"  # Nginx から Flask に接続するためにポート 5000 を開放
    volumes:
      - .:/app
    environment:
      FLASK_ENV: "development"
      FLASK_DEBUG: "True"
      SECRET_KEY: "mysecretkey"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app  # nginx だけが app に依存する
    restart: unless-stopped
